# Generated by Django 4.2.6 on 2023-10-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_requesting_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_req_contact', to='main.person')),
                ('preferred_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_person', to='main.person')),
            ],
        ),
    ]
