# Generated by Django 4.2.6 on 2023-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
