# Generated by Django 4.2.6 on 2024-02-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
